<?xml version="1.0"?>
<robot name="sorting_station" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <xacro:property name="prefix" value="line_"/>
  <xacro:property name="belt_height" value="0.50"/>
  <xacro:property name="belt_length" value="9.0"/>
  <xacro:property name="belt_width" value="0.5"/>
  <xacro:property name="support_radius" value="0.04"/>    <!-- Görsel kolon yarıçapı -->
  <xacro:property name="belt_support_height" value="0.50"/>   <!-- Bant altı kolon yüksekliği -->
  <xacro:property name="hopper_support_height" value="1.00"/> <!-- Huni kolon yüksekliği (daha uzun) -->
  <xacro:property name="support_color" value="0 0 0 1.0"/>    <!-- Kolon rengi (siyah) -->
  
  <!-- ============================================
       ÖLÇÜ KURALLARI (KESİN)
       ============================================ -->
  <!-- KAPI BOYUTLARI (tüm kapılar aynı) - DARALTILMIŞ -->
  <xacro:property name="gate_thickness" value="0.055"/>     <!-- Kapı kalınlığı (x ekseni) - minik kısaltıldı -->
  <xacro:property name="gate_arm_length" value="0.52"/>     <!-- Kol uzunluğu (banda doğru) - çok az kısaltıldı -->
  <xacro:property name="gate_height" value="0.24"/>         <!-- Kapı yüksekliği -->
  <xacro:property name="gate_hinge_offset" value="${gate_arm_length/2 - 0.01}"/> <!-- Hinge-to-tip mesafe (1cm pay) -->
  <xacro:property name="gate_joint_back_shift" value="${gate_arm_length/2 - 0.005}"/> <!-- Menteşe: gap arka kenarına ~5mm mesafe -->
  
  <!-- DUVAR BOŞLUKLARI (tüm istasyonlarda aynı) - KAPI UZUNLUĞU KADAR -->
  <xacro:property name="wall_gap_width" value="${gate_arm_length}"/>     <!-- Kapı süpürme uzunluğu kadar boşluk -->
  <xacro:property name="wall_gap_half" value="${wall_gap_width/2.0}"/>   <!-- Boşluğun yarısı -->
  
  <!-- MENTEŞİ NOKTALARI (banda yakın, duvar kenarı) -->
  <xacro:property name="gate_pivot_y_left" value="0.27"/>   <!-- LEFT kapı menteşesi -->
  <xacro:property name="gate_pivot_y_right" value="-0.27"/> <!-- RIGHT kapı menteşesi -->
  
  <!-- BASE PLATFORM -->
  <link name="${prefix}base_link">
    <visual>
      <origin xyz="0 0 0.025"/>
      <geometry><box size="12.0 5.0 0.05"/></geometry>
      <material name="BaseGrey"><color rgba="0.2 0.2 0.2 1"/></material>
    </visual>
    <collision>
      <origin xyz="0 0 0.025"/>
      <geometry><box size="12.0 5.0 0.05"/></geometry>
    </collision>
    <inertial>
      <mass value="100"/>
      <origin xyz="0 0 0.025"/>
      <inertia ixx="30" ixy="0" ixz="0" iyy="40" iyz="0" izz="50"/>
    </inertial>
  </link>

  <!-- MAIN CONVEYOR BELT -->
  <link name="${prefix}conveyor_belt">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry><box size="${belt_length} ${belt_width} 0.05"/></geometry>
      <material name="BeltBlack"><color rgba="0.05 0.05 0.05 1"/></material>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry><box size="${belt_length} ${belt_width} 0.05"/></geometry>
      <surface>
        <friction>
          <ode><mu>1.5</mu><mu2>1.5</mu2></ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <mass value="25"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="8" iyz="0" izz="6"/>
    </inertial>
  </link>

  <joint name="${prefix}conveyor_belt_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}conveyor_belt"/>
    <origin xyz="0 0 ${belt_height}"/>
  </joint>

  <gazebo reference="${prefix}conveyor_belt">
    <material>Gazebo/Grey</material>
    <mu1>1.5</mu1>
    <mu2>1.5</mu2>
  </gazebo>

  <!-- VISUAL SUPPORT COLUMNS (sadece görsel, hafif) -->
  <xacro:macro name="support_column" params="idx x y height">
    <link name="${prefix}support_${idx}">
      <visual>
        <origin xyz="0 0 ${height/2}"/>
        <geometry><cylinder length="${height}" radius="${support_radius}"/></geometry>
        <material name="SupportMat"><color rgba="${support_color}"/></material>
      </visual>
      <gazebo reference="${prefix}support_${idx}">
        <material>Gazebo/Black</material>
      </gazebo>
      <collision>
        <origin xyz="0 0 ${height/2}"/>
        <geometry><cylinder length="${height}" radius="0.001"/></geometry>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 ${height/2}"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>
    <joint name="${prefix}support_${idx}_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}support_${idx}"/>
      <origin xyz="${x} ${y} 0"/>
    </joint>
  </xacro:macro>

  <!-- Bant altı kolonlar -->
  <xacro:support_column idx="belt1" x="-4.0" y="0.0" height="${belt_support_height}"/>
  <xacro:support_column idx="belt2" x="-2.0" y="0.0" height="${belt_support_height}"/>
  <xacro:support_column idx="belt3" x="0.0"  y="0.0" height="${belt_support_height}"/>
  <xacro:support_column idx="belt4" x="2.0"  y="0.0" height="${belt_support_height}"/>
  <xacro:support_column idx="belt5" x="4.0"  y="0.0" height="${belt_support_height}"/>

  <!-- Huni/keçi ayağı kolonları -->
  <xacro:support_column idx="hopper_left"  x="-4.5" y="0.35"  height="${hopper_support_height}"/>
  <xacro:support_column idx="hopper_right" x="-4.5" y="-0.35" height="${hopper_support_height}"/>
  <xacro:support_column idx="hopper_back"  x="-4.9" y="0.0"   height="${hopper_support_height}"/>

  <!-- ============================================
       YAN DUVARLAR (KAPI POZİSYONLARINDA BOŞLUKLAR)
       ============================================
       KAPI POZİSYONLARI:
       LEFT (1,3,5):  x = -3.0, -0.6, 1.8
       RIGHT (2,4,6): x = -1.8, 0.6, 3.0
       Her boşluk: wall_gap_width = gate_arm_length (kapı süpürme uzunluğu kadar açık)
       ============================================ -->
  
  <xacro:macro name="wall_segment" params="side idx x_pos length">
    <link name="${prefix}belt_wall_${side}_seg${idx}">
      <visual>
        <origin xyz="0 0 0.08"/>
        <geometry><box size="${length} 0.04 0.12"/></geometry>
        <material name="WallGrey"><color rgba="0.6 0.6 0.6 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 0.08"/>
        <geometry><box size="${length} 0.04 0.12"/></geometry>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.02" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03"/>
      </inertial>
    </link>
    
    <joint name="${prefix}belt_wall_${side}_seg${idx}_joint" type="fixed">
      <parent link="${prefix}conveyor_belt"/>
      <child link="${prefix}belt_wall_${side}_seg${idx}"/>
      <xacro:if value="${side == 'left'}">
        <origin xyz="${x_pos} ${belt_width/2 + 0.02} 0"/>
      </xacro:if>
      <xacro:if value="${side == 'right'}">
        <origin xyz="${x_pos} ${-belt_width/2 - 0.02} 0"/>
      </xacro:if>
    </joint>
  </xacro:macro>
  
  <!-- LEFT WALL SEGMENTS (boşluklar x=-3.0, -0.6, 1.8) -->
  <!-- Her boşluk gate_arm_length (0.52m) genişlikte -->
  <xacro:wall_segment side="left" idx="1" x_pos="-3.88" length="1.24"/>    <!-- -4.5 to -3.26 -->
  <!-- GAP: -3.26 to -2.74 (0.52m) for gate1 at x=-3.0 -->
  <xacro:wall_segment side="left" idx="2" x_pos="-1.8" length="1.88"/>     <!-- -2.74 to -0.86 -->
  <!-- GAP: -0.86 to -0.34 (0.52m) for gate3 at x=-0.6 -->
  <xacro:wall_segment side="left" idx="3" x_pos="0.6" length="1.88"/>      <!-- -0.34 to 1.54 -->
  <!-- GAP: 1.54 to 2.06 (0.52m) for gate5 at x=1.8 -->
  <xacro:wall_segment side="left" idx="4" x_pos="3.28" length="2.44"/>     <!-- 2.06 to 4.5 -->
  
  <!-- RIGHT WALL SEGMENTS (boşluklar x=-1.8, 0.6, 3.0) -->
  <xacro:wall_segment side="right" idx="1" x_pos="-3.28" length="2.44"/>   <!-- -4.5 to -2.06 -->
  <!-- GAP: -2.06 to -1.54 (0.52m) for gate2 at x=-1.8 -->
  <xacro:wall_segment side="right" idx="2" x_pos="-0.6" length="1.88"/>    <!-- -1.54 to 0.34 -->
  <!-- GAP: 0.34 to 0.86 (0.52m) for gate4 at x=0.6 -->
  <xacro:wall_segment side="right" idx="3" x_pos="1.8" length="1.88"/>     <!-- 0.86 to 2.74 -->
  <!-- GAP: 2.74 to 3.26 (0.52m) for gate6 at x=3.0 -->
  <xacro:wall_segment side="right" idx="4" x_pos="3.88" length="1.24"/>    <!-- 3.26 to 4.5 -->

  <!-- HOPPER/FUNNEL -->
  <link name="${prefix}hopper_base">
    <inertial><mass value="0.1"/><inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/></inertial>
  </link>

  <joint name="${prefix}hopper_base_joint" type="fixed">
    <parent link="${prefix}conveyor_belt"/>
    <child link="${prefix}hopper_base"/>
    <origin xyz="-4.5 0 0.6"/>
  </joint>

  <link name="${prefix}hopper_wall_front">
    <visual>
      <geometry><box size="0.9 0.02 0.7"/></geometry>
      <material name="HopperWall"><color rgba="0.4 0.25 0.1 1.0"/></material>
    </visual>
    <gazebo reference="${prefix}hopper_wall_front">
      <material>Gazebo/Brown</material>
    </gazebo>
    <collision><geometry><box size="0.9 0.02 0.7"/></geometry></collision>
    <inertial><mass value="1"/><inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/></inertial>
  </link>
  <joint name="${prefix}hopper_wall_front_joint" type="fixed">
    <parent link="${prefix}hopper_base"/>
    <child link="${prefix}hopper_wall_front"/>
    <origin xyz="0 0.35 0.2" rpy="0.4 0 0"/>
  </joint>

  <link name="${prefix}hopper_wall_back">
    <visual>
      <geometry><box size="0.9 0.02 0.7"/></geometry>
      <material name="HopperWall"><color rgba="0.4 0.25 0.1 1.0"/></material>
    </visual>
    <gazebo reference="${prefix}hopper_wall_back">
      <material>Gazebo/Brown</material>
    </gazebo>
    <collision><geometry><box size="0.9 0.02 0.7"/></geometry></collision>
    <inertial><mass value="1"/><inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/></inertial>
  </link>
  <joint name="${prefix}hopper_wall_back_joint" type="fixed">
    <parent link="${prefix}hopper_base"/>
    <child link="${prefix}hopper_wall_back"/>
    <origin xyz="0 -0.35 0.2" rpy="-0.4 0 0"/>
  </joint>

  <link name="${prefix}hopper_wall_left">
    <visual>
      <geometry><box size="0.02 0.9 0.7"/></geometry>
      <material name="HopperWall"><color rgba="0.4 0.25 0.1 1.0"/></material>
    </visual>
    <gazebo reference="${prefix}hopper_wall_left">
      <material>Gazebo/Brown</material>
    </gazebo>
    <collision><geometry><box size="0.02 0.9 0.7"/></geometry></collision>
    <inertial><mass value="1"/><inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/></inertial>
  </link>
  <joint name="${prefix}hopper_wall_left_joint" type="fixed">
    <parent link="${prefix}hopper_base"/>
    <child link="${prefix}hopper_wall_left"/>
    <origin xyz="0.35 0 0.2" rpy="0 -0.4 0"/>
  </joint>

  <link name="${prefix}hopper_wall_right">
    <visual>
      <geometry><box size="0.02 0.9 0.7"/></geometry>
      <material name="HopperWall"><color rgba="0.4 0.25 0.1 1.0"/></material>
    </visual>
    <gazebo reference="${prefix}hopper_wall_right">
      <material>Gazebo/Brown</material>
    </gazebo>
    <collision><geometry><box size="0.02 0.9 0.7"/></geometry></collision>
    <inertial><mass value="1"/><inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/></inertial>
  </link>
  <joint name="${prefix}hopper_wall_right_joint" type="fixed">
    <parent link="${prefix}hopper_base"/>
    <child link="${prefix}hopper_wall_right"/>
    <origin xyz="-0.35 0 0.2" rpy="0 0.4 0"/>
  </joint>

  <!-- ═══════════════════════════════════════════════════════════════════
       SÜPÜRÜCÜ KAPILAR (SWEEPER GATES)
       
       ÖLÇÜ VE DAVRANLIŞ KURALLARI:
       ✓ TÜM KAPILAR AYNI BOYUTTA: 0.055m x 0.52m x 0.24m
       ✓ DEFAULT KAPALI BAŞLAR: angle = 0.0 rad
       ✓ ARKA UÇ SABİT: Menteşe duvar kenarında (y = ±0.27m)
       ✓ ÖN UÇ BANDA DOĞRU DÖNER: Bandın orta hattına kadar (~0.05m)
       ✓ SÜPÜRME HAREKETİ: 60-80° açılma (1.0-1.4 rad)
       ✓ MERKEZDİEN DEĞİL, ARKA UÇTAN DÖNER
       ══════════════════════════════════════════════════════════════════ -->
  
  <xacro:macro name="sweeper_gate" params="idx x side color_r color_g color_b">
    
    <!-- Kapı kolu (gate arm) -->
    <link name="${prefix}gate${idx}_link">
      <xacro:if value="${side > 0}">
        <!-- LEFT GATE: Menteşe y=+0.27, kol banda doğru (y=-direction) -->
        <visual>
          <!-- Kapı kolu X yönünde, menteşe boşluğun ileri ucunda (huniden uzak), serbest uç banda süpürür -->
          <origin xyz="${-(gate_arm_length/2 - 0.005)} 0 0" rpy="0 0 1.5708"/>
          <geometry><box size="${gate_thickness} ${gate_arm_length} ${gate_height}"/></geometry>
          <material name="Gate${idx}Color">
            <color rgba="${color_r} ${color_g} ${color_b} 1"/>
          </material>
        </visual>
        <collision>
          <origin xyz="${-(gate_arm_length/2 - 0.005)} 0 0" rpy="0 0 1.5708"/>
          <geometry><box size="${gate_thickness} ${gate_arm_length} ${gate_height}"/></geometry>
          <surface>
            <friction><ode><mu>3.0</mu><mu2>3.0</mu2></ode></friction>
          </surface>
        </collision>
        <inertial>
          <mass value="1.8"/>
          <origin xyz="${-(gate_arm_length/2 - 0.005)} 0 0" rpy="0 0 1.5708"/>
          <inertia ixx="0.05" ixy="0" ixz="0" iyy="0.006" iyz="0" izz="0.05"/>
        </inertial>
      </xacro:if>
      
      <xacro:if value="${side &lt; 0}">
        <!-- RIGHT GATE: Menteşe y=-0.27, kol banda doğru (y=+direction) -->
        <visual>
          <!-- Kapı kolu X yönünde, menteşe boşluğun ileri ucunda (huniden uzak), serbest uç banda süpürür -->
          <origin xyz="${-(gate_arm_length/2 - 0.005)} 0 0" rpy="0 0 1.5708"/>
          <geometry><box size="${gate_thickness} ${gate_arm_length} ${gate_height}"/></geometry>
          <material name="Gate${idx}Color">
            <color rgba="${color_r} ${color_g} ${color_b} 1"/>
          </material>
        </visual>
        <collision>
          <origin xyz="${-(gate_arm_length/2 - 0.005)} 0 0" rpy="0 0 1.5708"/>
          <geometry><box size="${gate_thickness} ${gate_arm_length} ${gate_height}"/></geometry>
          <surface>
            <friction><ode><mu>3.0</mu><mu2>3.0</mu2></ode></friction>
          </surface>
        </collision>
        <inertial>
          <mass value="1.8"/>
          <origin xyz="${-(gate_arm_length/2 - 0.005)} 0 0" rpy="0 0 1.5708"/>
          <inertia ixx="0.05" ixy="0" ixz="0" iyy="0.006" iyz="0" izz="0.05"/>
        </inertial>
      </xacro:if>
    </link>
    
    <!-- REVOLUTE JOINT: Menteşe banda yakın duvarda -->
    <joint name="gate${idx}_joint" type="revolute">
      <parent link="${prefix}conveyor_belt"/>
      <child link="${prefix}gate${idx}_link"/>
      <axis xyz="0 0 1"/>  <!-- Dikey eksen etrafında dönme -->
      <dynamics damping="0.6" friction="0.12"/>
      
      <xacro:if value="${side > 0}">
        <!-- LEFT GATE: Menteşe y=+0.27m (duvar kenarı) -->
        <origin xyz="${x + gate_joint_back_shift} ${gate_pivot_y_left} 0.16" rpy="0 0 0"/>
        <!-- Kapalı: 0.0, Açık: +1.3 rad (~75°, banda doğru süpürme sağa) -->
        <limit lower="-0.02" upper="1.35" effort="180" velocity="5.5"/>
      </xacro:if>
      
      <xacro:if value="${side &lt; 0}">
        <!-- RIGHT GATE: Menteşe y=-0.27m (duvar kenarı) -->
        <origin xyz="${x + gate_joint_back_shift} ${gate_pivot_y_right} 0.16" rpy="0 0 0"/>
        <!-- Kapalı: 0.0, Açık: -1.3 rad (~75°, banda doğru süpürme sola) -->
        <limit lower="-1.35" upper="0.02" effort="180" velocity="5.5"/>
      </xacro:if>
    </joint>
    
    <gazebo reference="${prefix}gate${idx}_link">
      <material>Gazebo/Orange</material>
      <mu1>3.0</mu1>
      <mu2>3.0</mu2>
    </gazebo>
  </xacro:macro>

  <!-- 6 Kapı tanımları (TÜM KAPILAR AYNI BOYUTTA) -->
  <xacro:sweeper_gate idx="1" x="-3.0" side="1"  color_r="1.0" color_g="0.5" color_b="0.0"/>
  <xacro:sweeper_gate idx="3" x="-0.6" side="1"  color_r="1.0" color_g="0.5" color_b="0.0"/>
  <xacro:sweeper_gate idx="5" x="1.8"  side="1"  color_r="1.0" color_g="0.5" color_b="0.0"/>
  
  <!-- Sağ kapılar için sağa doğru pozitif açı yerine negatif açıyla içeri süpürme (limitler üstte aynı) -->
  <xacro:sweeper_gate idx="2" x="-1.8" side="-1" color_r="1.0" color_g="0.5" color_b="0.0"/>
  <xacro:sweeper_gate idx="4" x="0.6"  side="-1" color_r="1.0" color_g="0.5" color_b="0.0"/>
  <xacro:sweeper_gate idx="6" x="3.0"  side="-1" color_r="1.0" color_g="0.5" color_b="0.0"/>

  <!-- SIDE CHANNELS -->
  <xacro:macro name="slide_channel" params="idx x y yaw">
    <link name="${prefix}channel${idx}_link">
      <visual>
        <geometry><box size="1.5 0.45 0.04"/></geometry>
        <material name="ChannelRed">
          <color rgba="0.8 0.1 0.1 0.8"/>
        </material>
      </visual>
      <collision>
        <geometry><box size="1.5 0.45 0.04"/></geometry>
        <surface>
          <friction>
            <ode><mu>0.15</mu><mu2>0.15</mu2></ode>
          </friction>
        </surface>
      </collision>
      <inertial>
        <mass value="4"/>
        <inertia ixx="0.4" ixy="0" ixz="0" iyy="0.5" iyz="0" izz="0.5"/>
      </inertial>
    </link>

    <!-- Yan set: kutuların kanaldan düşmesini engelleyen alçak duvarlar -->
    <link name="${prefix}channel${idx}_side_left">
      <visual>
        <geometry><box size="1.5 0.03 0.12"/></geometry>
        <material name="ChannelSide"><color rgba="0 0 0 1"/></material>
      </visual>
      <collision>
        <geometry><box size="1.5 0.03 0.12"/></geometry>
      </collision>
      <inertial><mass value="0.5"/><inertia ixx="0.02" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03"/></inertial>
    </link>

    <link name="${prefix}channel${idx}_side_right">
      <visual>
        <geometry><box size="1.5 0.03 0.12"/></geometry>
        <material name="ChannelSide"><color rgba="0 0 0 1"/></material>
      </visual>
      <collision>
        <geometry><box size="1.5 0.03 0.12"/></geometry>
      </collision>
      <inertial><mass value="0.5"/><inertia ixx="0.02" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03"/></inertial>
    </link>
    
    <joint name="${prefix}channel${idx}_joint" type="fixed">
      <parent link="${prefix}conveyor_belt"/>
      <child link="${prefix}channel${idx}_link"/>
      <origin xyz="${x} ${y} -0.21" rpy="0 0.28 ${yaw}"/>
    </joint>

    <!-- Yan setleri bağla: ana kanalın kenarına, hafif yükseltilmiş -->
    <joint name="${prefix}channel${idx}_side_left_joint" type="fixed">
      <parent link="${prefix}channel${idx}_link"/>
      <child link="${prefix}channel${idx}_side_left"/>
      <origin xyz="0 0.21 0.06" rpy="0 0 0"/>
    </joint>

    <joint name="${prefix}channel${idx}_side_right_joint" type="fixed">
      <parent link="${prefix}channel${idx}_link"/>
      <child link="${prefix}channel${idx}_side_right"/>
      <origin xyz="0 -0.21 0.06" rpy="0 0 0"/>
    </joint>
    
    <gazebo reference="${prefix}channel${idx}_link">
      <material>Gazebo/Red</material>
      <mu1>0.15</mu1>
      <mu2>0.15</mu2>
    </gazebo>
  </xacro:macro>

  <xacro:slide_channel idx="1" x="-3.0" y="1.0"  yaw="1.5708"/>
  <xacro:slide_channel idx="2" x="-1.8" y="-1.0" yaw="-1.5708"/>
  <xacro:slide_channel idx="3" x="-0.6" y="1.0"  yaw="1.5708"/>
  <xacro:slide_channel idx="4" x="0.6"  y="-1.0" yaw="-1.5708"/>
  <xacro:slide_channel idx="5" x="1.8"  y="1.0"  yaw="1.5708"/>
  <xacro:slide_channel idx="6" x="3.0"  y="-1.0" yaw="-1.5708"/>

  <!-- CONTAINERS -->
  <xacro:macro name="container" params="idx x y r g b name entry_side gazebo_mat">
    <link name="${prefix}container${idx}_bottom">
      <visual>
        <geometry><box size="0.8 0.8 0.05"/></geometry>
        <material name="Container${idx}Mat"><color rgba="${r} ${g} ${b} 1.0"/></material>
      </visual>
      <collision><geometry><box size="0.8 0.8 0.05"/></geometry></collision>
      <inertial><mass value="5"/><inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.15"/></inertial>
    </link>
    <gazebo reference="${prefix}container${idx}_bottom">
      <material>${gazebo_mat}</material>
    </gazebo>
    <joint name="${prefix}container${idx}_bottom_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}container${idx}_bottom"/>
      <origin xyz="${x} ${y} 0.075"/>
    </joint>

    <xacro:macro name="container_wall" params="wall_name pose_x pose_y size_x size_y">
      <link name="${prefix}container${idx}_${wall_name}">
        <visual>
          <geometry><box size="${size_x} ${size_y} 0.5"/></geometry>
          <material name="Container${idx}Mat"><color rgba="${r} ${g} ${b} 1.0"/></material>
        </visual>
        <collision><geometry><box size="${size_x} ${size_y} 0.5"/></geometry></collision>
        <inertial><mass value="2"/><inertia ixx="0.06" ixy="0" ixz="0" iyy="0.06" iyz="0" izz="0.08"/></inertial>
      </link>
      <gazebo reference="${prefix}container${idx}_${wall_name}">
        <material>${gazebo_mat}</material>
      </gazebo>
      <joint name="${prefix}container${idx}_${wall_name}_joint" type="fixed">
        <parent link="${prefix}container${idx}_bottom"/>
        <child link="${prefix}container${idx}_${wall_name}"/>
        <origin xyz="${pose_x} ${pose_y} 0.25"/>
      </joint>
    </xacro:macro>

    <!-- Duvara giriş deliği için özel duvar -->
    <xacro:macro name="container_wall_with_hole" params="wall_name pose_x pose_y size_x size_y hole_w hole_h">
      <!-- Yan sütunlar -->
      <link name="${prefix}container${idx}_${wall_name}_pillar_left">
        <visual>
          <geometry><box size="${(size_x-hole_w)/2} ${size_y} 0.5"/></geometry>
          <material name="Container${idx}Mat"><color rgba="${r} ${g} ${b} 1.0"/></material>
        </visual>
        <collision><geometry><box size="${(size_x-hole_w)/2} ${size_y} 0.5"/></geometry></collision>
        <inertial><mass value="0.8"/><inertia ixx="0.04" ixy="0" ixz="0" iyy="0.04" iyz="0" izz="0.05"/></inertial>
      </link>
      <gazebo reference="${prefix}container${idx}_${wall_name}_pillar_left">
        <material>${gazebo_mat}</material>
      </gazebo>
      <joint name="${prefix}container${idx}_${wall_name}_pillar_left_joint" type="fixed">
        <parent link="${prefix}container${idx}_bottom"/>
        <child link="${prefix}container${idx}_${wall_name}_pillar_left"/>
        <origin xyz="${-hole_w/2 - (size_x-hole_w)/4} ${pose_y} 0.25"/>
      </joint>

      <link name="${prefix}container${idx}_${wall_name}_pillar_right">
        <visual>
          <geometry><box size="${(size_x-hole_w)/2} ${size_y} 0.5"/></geometry>
          <material name="Container${idx}Mat"><color rgba="${r} ${g} ${b} 1.0"/></material>
        </visual>
        <collision><geometry><box size="${(size_x-hole_w)/2} ${size_y} 0.5"/></geometry></collision>
        <inertial><mass value="0.8"/><inertia ixx="0.04" ixy="0" ixz="0" iyy="0.04" iyz="0" izz="0.05"/></inertial>
      </link>
      <gazebo reference="${prefix}container${idx}_${wall_name}_pillar_right">
        <material>${gazebo_mat}</material>
      </gazebo>
      <joint name="${prefix}container${idx}_${wall_name}_pillar_right_joint" type="fixed">
        <parent link="${prefix}container${idx}_bottom"/>
        <child link="${prefix}container${idx}_${wall_name}_pillar_right"/>
        <origin xyz="${hole_w/2 + (size_x-hole_w)/4} ${pose_y} 0.25"/>
      </joint>

      <!-- Üst lento: deliğin üstünü kapatır -->
      <link name="${prefix}container${idx}_${wall_name}_lintel">
        <visual>
          <geometry><box size="${hole_w} ${size_y} ${0.5 - hole_h}"/></geometry>
          <material name="Container${idx}Mat"><color rgba="${r} ${g} ${b} 1.0"/></material>
        </visual>
        <collision><geometry><box size="${hole_w} ${size_y} ${0.5 - hole_h}"/></geometry></collision>
        <inertial><mass value="0.8"/><inertia ixx="0.04" ixy="0" ixz="0" iyy="0.04" iyz="0" izz="0.05"/></inertial>
      </link>
      <gazebo reference="${prefix}container${idx}_${wall_name}_lintel">
        <material>${gazebo_mat}</material>
      </gazebo>
      <joint name="${prefix}container${idx}_${wall_name}_lintel_joint" type="fixed">
        <parent link="${prefix}container${idx}_bottom"/>
        <child link="${prefix}container${idx}_${wall_name}_lintel"/>
        <origin xyz="0 ${pose_y} ${(0.5 + hole_h)/2}"/>
      </joint>
    </xacro:macro>

    <!-- Standart yan duvarlar + giriş duvarı -->
    <xacro:if value="${entry_side == 'back'}">
      <xacro:container_wall wall_name="front" pose_x="0" pose_y="0.375" size_x="0.8" size_y="0.05"/>
      <xacro:container_wall_with_hole wall_name="back" pose_x="0" pose_y="-0.375" size_x="0.8" size_y="0.05" hole_w="0.4" hole_h="0.3"/>
    </xacro:if>
    <xacro:if value="${entry_side == 'front'}">
      <xacro:container_wall_with_hole wall_name="front" pose_x="0" pose_y="0.375" size_x="0.8" size_y="0.05" hole_w="0.4" hole_h="0.3"/>
      <xacro:container_wall wall_name="back" pose_x="0" pose_y="-0.375" size_x="0.8" size_y="0.05"/>
    </xacro:if>
    <xacro:container_wall wall_name="left" pose_x="0.375" pose_y="0" size_x="0.05" size_y="0.8"/>
    <xacro:container_wall wall_name="right" pose_x="-0.375" pose_y="0" size_x="0.05" size_y="0.8"/>

    <!-- Kapak (üstü kapalı) -->
    <link name="${prefix}container${idx}_top">
      <visual>
        <geometry><box size="0.8 0.8 0.03"/></geometry>
        <material name="Container${idx}Mat"><color rgba="${r} ${g} ${b} 1.0"/></material>
      </visual>
      <collision><geometry><box size="0.8 0.8 0.03"/></geometry></collision>
      <inertial><mass value="0.8"/><inertia ixx="0.04" ixy="0" ixz="0" iyy="0.04" iyz="0" izz="0.04"/></inertial>
    </link>
    <joint name="${prefix}container${idx}_top_joint" type="fixed">
      <parent link="${prefix}container${idx}_bottom"/>
      <child link="${prefix}container${idx}_top"/>
      <origin xyz="0 0 0.515"/>
    </joint>
    <gazebo reference="${prefix}container${idx}_top">
      <material>${gazebo_mat}</material>
    </gazebo>
  </xacro:macro>

  <!-- entry_side: rampanın geldiği yüz; y>0 konteynerlerde back, y<0 konteynerlerde front -->
  <xacro:container idx="1" x="-3.0" y="2.0" r="1.0" g="1.0" b="1.0" name="Metal"   entry_side="back"  gazebo_mat="Gazebo/White"/>
  <xacro:container idx="2" x="-1.8" y="-2.0" r="0.2" g="0.4" b="0.9" name="Plastic" entry_side="front" gazebo_mat="Gazebo/Blue"/>
  <xacro:container idx="3" x="-0.6" y="2.0" r="0.2" g="0.8" b="0.3" name="Glass"   entry_side="back"  gazebo_mat="Gazebo/Green"/>
  <xacro:container idx="4" x="0.6" y="-2.0" r="0.9" g="0.8" b="0.2" name="Paper"   entry_side="front" gazebo_mat="Gazebo/Yellow"/>
  <xacro:container idx="5" x="1.8" y="2.0" r="0.6" g="0.2" b="0.8" name="Battery"  entry_side="back"  gazebo_mat="Gazebo/Purple"/>
  <xacro:container idx="6" x="3.0" y="-2.0" r="0.9" g="0.3" b="0.2" name="Organic" entry_side="front" gazebo_mat="Gazebo/Orange"/>

  <!-- GRINDER BIN (Unclassified waste) -->
  <link name="${prefix}grinder_bin_base">
    <visual>
      <geometry><box size="0.6 0.6 0.05"/></geometry>
      <material name="GrinderGrey"><color rgba="0.2 0.2 0.2 1"/></material>
    </visual>
    <collision><geometry><box size="0.6 0.6 0.05"/></geometry></collision>
    <inertial><mass value="4"/><inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/></inertial>
  </link>
  <joint name="${prefix}grinder_bin_base_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}grinder_bin_base"/>
    <origin xyz="4.6 0 0.05"/>
  </joint>

  <xacro:macro name="grinder_wall" params="name pose_x pose_y size_x size_y">
    <link name="${prefix}grinder_${name}">
      <visual>
        <geometry><box size="${size_x} ${size_y} 0.35"/></geometry>
        <material name="GrinderGrey"><color rgba="0.2 0.2 0.2 1"/></material>
      </visual>
      <collision><geometry><box size="${size_x} ${size_y} 0.35"/></geometry></collision>
      <inertial><mass value="2"/><inertia ixx="0.08" ixy="0" ixz="0" iyy="0.08" iyz="0" izz="0.1"/></inertial>
    </link>
    <joint name="${prefix}grinder_${name}_joint" type="fixed">
      <parent link="${prefix}grinder_bin_base"/>
      <child link="${prefix}grinder_${name}"/>
      <origin xyz="${pose_x} ${pose_y} 0.2"/>
    </joint>
  </xacro:macro>

  <!-- Öğütücü: tüm duvarlar (üstü açık), kısa yükseklik -->
  <xacro:grinder_wall name="front" pose_x="0" pose_y="0.275" size_x="0.6" size_y="0.05"/>
  <xacro:grinder_wall name="back"  pose_x="0" pose_y="-0.275" size_x="0.6" size_y="0.05"/>
  <xacro:grinder_wall name="left"  pose_x="0.275" pose_y="0" size_x="0.05" size_y="0.6"/>
  <xacro:grinder_wall name="right" pose_x="-0.275" pose_y="0" size_x="0.05" size_y="0.6"/>

  <!-- ============================================
       KAMERA (BANDA YAKIN, SADECE BANT GÖRSİN)
       ============================================ -->
  <link name="${prefix}camera_link">
    <visual>
      <geometry><cylinder length="0.10" radius="0.06"/></geometry>
      <material name="CameraBlack"><color rgba="0.1 0.1 0.1 1"/></material>
    </visual>
    <collision><geometry><cylinder length="0.10" radius="0.06"/></geometry></collision>
    <inertial><mass value="0.6"/><inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/></inertial>
  </link>

  <joint name="${prefix}camera_joint" type="fixed">
    <parent link="${prefix}conveyor_belt"/>
    <child link="${prefix}camera_link"/>
    <!-- Banda daha yakın: x=-3.9, z=0.54, pitch daha dik (1.05 rad ~60°) -->
    <origin xyz="-3.9 0 0.54" rpy="0 1.05 0"/>
  </joint>

  <gazebo reference="${prefix}camera_link">
    <sensor type="camera" name="sorting_camera">
      <always_on>true</always_on>
      <update_rate>20</update_rate>
      <camera>
        <!-- Daha dar görüş açısı - sadece bant -->
        <horizontal_fov>0.8</horizontal_fov>
        <image>
          <width>800</width>
          <height>600</height>
          <format>R8G8B8</format>
        </image>
        <!-- Daha yakın clipping - duvarları görmemek için -->
        <clip><near>0.12</near><far>2.5</far></clip>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <robotNamespace>/</robotNamespace>
        <cameraName>camera</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <frameName>${prefix}camera_link</frameName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- TRANSMISSIONS -->
  <xacro:macro name="gate_transmission" params="idx">
    <transmission name="gate${idx}_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="gate${idx}_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="gate${idx}_motor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <xacro:gate_transmission idx="1"/>
  <xacro:gate_transmission idx="2"/>
  <xacro:gate_transmission idx="3"/>
  <xacro:gate_transmission idx="4"/>
  <xacro:gate_transmission idx="5"/>
  <xacro:gate_transmission idx="6"/>

  <!-- ROS CONTROL -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>

</robot>
